### PR TITLE
Rename install-dependancies to install-dependencies

### PR DESCRIPTION
**Pull request by zevaverbach**

### CODE REVIEW

**Comment by ssshake** [comment]
Thanks for contributing. Never thought anyone would actually check this out :) If you have any additions or improvements you would like to make please do.

**Comment by zevaverbach** [comment]
:)  My pleasure.  I'll let you know about additions/improvements once my kids get a little older.  (no, probably sooner)

**Comment by zevaverbach** [comment]
btw do you have kids/students that have used these?  any suggestion as to how to go about it?

**Comment by ssshake** [comment]
No not really. I haven't touched this for a while. I wrote this to show my nephew that there is fun to be had on a computer without all the pretty graphics. Never really got around to exposing him to it.

**Pull request merged**
